# Generated by Django 3.0.3 on 2020-12-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_mock', '0002_balancehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
