# Generated by Django 3.0.3 on 2020-12-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_mock', '0003_auto_20201226_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
